version: '3.8'

services:
  frontend-react:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend-php:
    build:
      context: ./backend-php
      dockerfile: Dockerfile
    ports:
      - "8000:80"
