version: '3.8'

services:
  frontend-react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app

  backend-php:
    build:
      context: ../backend-php
      dockerfile: Dockerfile
    ports:
      - "8000:80"
